format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $haskell\
    $java\
    $julia\
    $nim\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $crystal\
    $kubernetes\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
    """

# [character]      # The name of the module we are configuring is "character"
# symbol = "➜"     # The "symbol" segment is being set to "➜"

[package]
disabled = true

[kubernetes]
symbol = "☸ "
format = "on [$symbol$context( \\($namespace\\))]($style) "
disabled = false


