format = """\
    $username\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $kubernetes\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $character\
    """

[jobs]
symbol = "★"

[kubernetes]
symbol = "☸"
format = "on [$symbol $context( \\($namespace\\))]($style) "
disabled = false

