format = """\
    $username\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $kubernetes\
    $gcloud\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $character\
    """

[directory]
truncate_to_repo = false

[jobs]
symbol = "★"

[kubernetes]
symbol = "☸ "
format = "in [$context( \\($namespace\\))]($style) "
disabled = false

[gcloud]
symbol = "☁️"
format = "on [$project]($style) "
